### ISSUE TITLE
PHP 7.3 install failure on M1 MacBook Air

### ISSUE THREAD

**Issue by boogah** [philipnewcomer/localhost#1]
This looks great! Excited to try it! Only problem is, Homebrew doesn't seem to want to install `php@7.3` on a brand new M1 MacBook Air. Here's what I get when running `localhost install`:

```
Installing PHP 7.3: failed

In CommandLine.php line 19:

  brew install php@7.3 failed with exit code 1.
```

Trying to run `brew install php@7.3` gives me this:

```
Error: php@7.3: no bottle available!
You can try to install from source with:
  brew install --build-from-source php@7.3
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

I could try to do a self-build where I've dropped PHP 7.3.x support, but I thought I'd hit you up first.

**Comment by philipnewcomer** [comment]
Hey, thanks for the feedback! Apparently PHP 7.3 [isn't available for M1 through Homebrew](https://doesitarm.com/formula/php@7.3/), and given that PHP 7.3's end-of-life is just a couple months away, I doubt it will be.

I don't have an M1 Mac to test this project on, but I've created a new branch `apple-silicon`, where I've removed PHP 7.3. Hopefully that will work for you. You can download that build manually (https://github.com/philipnewcomer/localhost/blob/apple-silicon/builds/localhost) and use it instead of the default build.

Let me know if that works. Since PHP 7.3's end of life [is coming up shortly](https://www.php.net/supported-versions.php) on 2022-01-01, I'll be removing PHP 7.3 from the main project at that time, so hopefully I won't need to maintain two versions of the project (Intel silicon and Apple silicon) for long.

I'm going to leave this issue open and pin it for now for visibility in case anyone else tries to use the project on an Apple Silicon mac.

**Comment by philipnewcomer** [comment]
Update: I've updated the install script on the `apple-silicon` branch to download the proper build for that platform, so you don't need to manually download anything. Just [switch to the apple-silicon branch](https://github.com/philipnewcomer/localhost/tree/apple-silicon) and run the install script found there.

**Comment by philipnewcomer** [comment]
Closing as PHP 7.3 support has now been removed from Localhost regardless of architecture.
